version: "3.9" 
services:
  showapi:
    container_name: showapi
    build:
      context: ../../code/showApi
      dockerfile: ../../code/showApi/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: always
  ticketapi:
    container_name: ticketapi
    build:
      context: ../../code/ticketsapi
      dockerfile: ../../code/ticketsapi/Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .env
    restart: always
  frontend:
    container_name: "frontend"
    build:
      context: "../../code/React frontend"
      dockerfile: "../../code/React frontend/Dockerfile"
    ports:
      - "3000:3000"
    restart: always
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ../reverse_proxy
      dockerfile: ../reverse_proxy/Dockerfile
    ports:
      - 80:80
    depends_on:
      - ticketapi
      - showapi
      - frontend
      - laakdb
      - firefox
  laakdb:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: laakdb
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    restart: always
  firefox:
    image: overclockedllama/docker-chromium
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/chromium:/config:rw"