version: "3.9" 
services:
  showapi:
    container_name: showapi
    build:
      context: ../../code/showApi
      dockerfile: ../../code/showApi/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: always
  ticketapi:
    container_name: ticketapi
    build:
      context: ../../code/ticketsapi
      dockerfile: ../../code/ticketsapi/Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .env
    restart: always
  frontend:
    container_name: "frontend"
    build:
      context: "../../code/React frontend"
      dockerfile: "../../code/React frontend/Dockerfile"
    ports:
      - "3000:3000"
    restart: always
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ../reverse_proxy
      dockerfile: ../reverse_proxy/Dockerfile
    ports:
      - 80:80
    depends_on:
      - ticketapi
      - showapi
      - frontend
      - laakdb
  laakdb:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: laakdb
    ports:
      - "1439:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${SA_PASSWORD}
    env_file:
      - .env
    restart: always
  ide:
    image: psharkey/intellij:latest
#    image: psharkey/netbeans-8.1:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: psharkey/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8089:8080"
    networks:
      - x11
networks:
  x11: