version: "3.9" 
services:
  showapi:
    container_name: showapi
    build:
      context: ../../code/showApi
      dockerfile: ../../code/showApi/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: always
  ticketapi:
    container_name: ticketapi
    build:
      context: ../../code/ticketsapi
      dockerfile: ../../code/ticketsapi/Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .env
    restart: always

  auth:
    container_name: auth
    build:
      context: ../../code/auth
      dockerfile: ../../code/auth/Dockerfile
    ports:
      - "8082:80"
    environment:
      - SigningKey=${SigningKey}
      - TEST="test"
    env_file:
      - .env
    restart: always  
  todoapi:
    container_name: todoapi
    build:
      context: ../../code/TodoApi
      dockerfile: ../../code/TodoApi/Dockerfile
    ports:
      - "8083:80"
    environment:
      - SigningKey=${SigningKey}
      - TEST="test"

    env_file:
      - .env
    restart: always  
  frontend:
    container_name: "frontend"
    build:
      context: "../../code/React frontend"
      dockerfile: "../../code/React frontend/Dockerfile"
    ports:
      - "3000:3000"
    restart: always
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ../reverse_proxy
      dockerfile: ../reverse_proxy/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ticketapi
      - showapi
      - frontend
      - laakdb
      - auth
      - todoapi
  laakdb:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: laakdb
    ports:
      - "1439:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${SA_PASSWORD}
    env_file:
      - .env
    restart: always