version: "3.9"  # optional since v1.27.0
services:
  # todoapi:
  #   container_name: todoapi
  #   build:
  #     context: ../../code/TodoApi
  #     dockerfile: ../../code/TodoApi/Dockerfile
  #   ports:
  #     - "8080:80"
  #   restart: always
  frontend:
    container_name: "frontend"
    build:
      context: "../../code/React frontend"
      dockerfile: "../../code/React frontend/Dockerfile"
    ports:
      - "3000:3000"
    restart: always
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ../reverse_proxy
      dockerfile: ../reverse_proxy/Dockerfile
    ports:
      - 80:80
    depends_on:
      # - todoapi
      - frontend