name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        # Run your tests here
        echo "Running tests..."
    - name: Create environment file
      run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          # Run commands to deploy code to your Raspberry Pi here
          echo "Deploying code to Raspberry Pi..."
          cd theaterLaak
          git pull
          cd deployment
          cd docker-compose
          echo "Running docker compose"
          sudo docker-compose up -d --build
          cd ..
          cd ..
          cd code
          cd showApi
          dotnet ef database update
          cd ..
          cd ticketsapi
          dotnet ef database update
