name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        # Run your tests here
        echo "Running tests..."


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v0.1.7
      env:
        SAPASSWORD: ${{ secrets.DB_PASSWORD }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          # Run commands to deploy code to your Raspberry Pi here
          echo "Deploying code to Raspberry Pi..."
          export SAPASSWORD=${{ secrets.DB_PASSWORD }}
          cd theaterLaak
          git fetch --all
          git reset --hard origin/main
          git pull --force
          cd deployment
          cd reverse_proxy
          echo "${{ secrets.SSL_KEY }}" >> mohieddin.nl.key
          echo "${{ secrets.SSL.CERT }}" >> mohieddin.nl.pem
          cd ..
          cd docker-compose
          echo "SA_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "Running docker compose"
          sudo docker-compose up -d --build --remove-orphans
          echo "removing env file"
          cat .env
          rm .env
          cd ..
          cd reverse_proxy
          rm mohieddin.nl.key
          rm mohieddin.nl.pem